"""
Comfyui-TOO-Pack
A custom nodes pack for ComfyUI
"""
from .nodes.image.smart_image_loader import NODE_CLASS_MAPPINGS as SMART_IMAGE_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SMART_IMAGE_LOADER_DISPLAY_MAPPINGS
from .nodes.image.smart_image_saver import NODE_CLASS_MAPPINGS as SMART_IMAGE_SAVER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SMART_IMAGE_SAVER_DISPLAY_MAPPINGS
from .nodes.image.too_image_metadata import NODE_CLASS_MAPPINGS as TOO_IMAGE_METADATA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TOO_IMAGE_METADATA_DISPLAY_MAPPINGS
from .nodes.utils.extract_widget_from_node import NODE_CLASS_MAPPINGS as EXTRACT_WIDGET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EXTRACT_WIDGET_DISPLAY_MAPPINGS
from .nodes.utils.collection_categorizer import NODE_CLASS_MAPPINGS as COLLECTION_CATEGORIZER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COLLECTION_CATEGORIZER_DISPLAY_MAPPINGS
from .nodes.mixlab.color_input import NODE_CLASS_MAPPINGS as COLOR_INPUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COLOR_INPUT_DISPLAY_MAPPINGS
from .nodes.mixlab.load_images_from_url import NODE_CLASS_MAPPINGS as LOAD_IMAGES_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGES_DISPLAY_MAPPINGS
from .nodes.image.warmth_tint_color_correction import NODE_CLASS_MAPPINGS as WARMTH_TINT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WARMTH_TINT_DISPLAY_MAPPINGS
from .nodes.image.krita_bridge import NODE_CLASS_MAPPINGS as KRITA_BRIDGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as KRITA_BRIDGE_DISPLAY_MAPPINGS
from .nodes.utils.view_combo import NODE_CLASS_MAPPINGS as VIEW_COMBO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIEW_COMBO_DISPLAY_MAPPINGS
from .nodes.utils.preset_text import NODE_CLASS_MAPPINGS as PRESET_TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PRESET_TEXT_DISPLAY_MAPPINGS
from .nodes.utils.lora_queue_helper import NODE_CLASS_MAPPINGS as LORA_QUEUE_HELPER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LORA_QUEUE_HELPER_DISPLAY_MAPPINGS
from .nodes.utils.too_much_replace import NODE_CLASS_MAPPINGS as TOO_MUCH_REPLACE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TOO_MUCH_REPLACE_DISPLAY_MAPPINGS
from .nodes.image.smart_image_saver_adv_naming import NODE_CLASS_MAPPINGS as FILE_NAMING_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FILE_NAMING_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **SMART_IMAGE_LOADER_MAPPINGS,
    **SMART_IMAGE_SAVER_MAPPINGS,
    **TOO_IMAGE_METADATA_MAPPINGS,
    **EXTRACT_WIDGET_MAPPINGS,
    **COLLECTION_CATEGORIZER_MAPPINGS,
    **LOAD_IMAGES_MAPPINGS,
    **COLOR_INPUT_MAPPINGS,
    **WARMTH_TINT_MAPPINGS,
    **KRITA_BRIDGE_MAPPINGS,
    **VIEW_COMBO_MAPPINGS,
    **PRESET_TEXT_MAPPINGS,
    **LORA_QUEUE_HELPER_MAPPINGS,
    **TOO_MUCH_REPLACE_MAPPINGS,
    **FILE_NAMING_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SMART_IMAGE_LOADER_DISPLAY_MAPPINGS,
    **SMART_IMAGE_SAVER_DISPLAY_MAPPINGS,
    **TOO_IMAGE_METADATA_DISPLAY_MAPPINGS,
    **EXTRACT_WIDGET_DISPLAY_MAPPINGS,
    **COLLECTION_CATEGORIZER_DISPLAY_MAPPINGS,
    **LOAD_IMAGES_DISPLAY_MAPPINGS,
    **COLOR_INPUT_DISPLAY_MAPPINGS,
    **WARMTH_TINT_DISPLAY_MAPPINGS,
    **KRITA_BRIDGE_DISPLAY_MAPPINGS,
    **VIEW_COMBO_DISPLAY_MAPPINGS,
    **PRESET_TEXT_DISPLAY_MAPPINGS,
    **LORA_QUEUE_HELPER_DISPLAY_MAPPINGS,
    **TOO_MUCH_REPLACE_DISPLAY_MAPPINGS,
    **FILE_NAMING_DISPLAY_MAPPINGS,
}

# Define the web directory for ComfyUI to find our JavaScript files
WEB_DIRECTORY = "./web"

# Define extension web directories for icons
EXTENSION_WEB_DIRS = {
    "TOO-Pack": WEB_DIRECTORY
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']